# Generated by Django 3.0.8 on 2020-07-22 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_mainnav'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mainnav',
            table='axf_nav',
        ),
    ]
