# Generated by Django 3.0.8 on 2020-07-23 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_foodetype'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='foodetype',
            table='axf_foodtype',
        ),
    ]
