# Generated by Django 3.0.8 on 2020-07-23 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_auto_20200723_1515'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FoodeType',
            new_name='FoodType',
        ),
    ]
